# Site settings
title: A website about Elaheh(Elli) Mola, software engineer,https://elahehmo.github.io/elli/ 
description:
# baseurl: "//" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Elaheh Mola	
user_title: for things to change for you, you've got to change(Jim Rohn)
user_description: 
 I am  designer, developer and travel enthusiast. I believe we are brought to this world to grow and success. Success is far away from comfort zone and that is why I care about personal development.
email: anon@anon.com
twitter_username: elahehmola
github_username:  elahehmo	


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']